// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRtYgTKv7WxyDUZYYlXRh0oh8XtdXKQlI',
    appId: '1:692156371176:web:5f5f072229cf48bf60795d',
    messagingSenderId: '692156371176',
    projectId: 'comments-d4079',
    authDomain: 'comments-d4079.firebaseapp.com',
    storageBucket: 'comments-d4079.appspot.com',
    measurementId: 'G-KPTYM2BHDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn1BMYtiOnP5x5OZuzOU_s7chmooTy27c',
    appId: '1:692156371176:android:52ae24719d5fb07760795d',
    messagingSenderId: '692156371176',
    projectId: 'comments-d4079',
    storageBucket: 'comments-d4079.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWBdA1nMEWVv73xzm9wlc2qx2Az3-isow',
    appId: '1:692156371176:ios:edaf3f7943273b2e60795d',
    messagingSenderId: '692156371176',
    projectId: 'comments-d4079',
    storageBucket: 'comments-d4079.appspot.com',
    iosBundleId: 'com.example.comments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWBdA1nMEWVv73xzm9wlc2qx2Az3-isow',
    appId: '1:692156371176:ios:edaf3f7943273b2e60795d',
    messagingSenderId: '692156371176',
    projectId: 'comments-d4079',
    storageBucket: 'comments-d4079.appspot.com',
    iosBundleId: 'com.example.comments',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRtYgTKv7WxyDUZYYlXRh0oh8XtdXKQlI',
    appId: '1:692156371176:web:343ce4ec2553137d60795d',
    messagingSenderId: '692156371176',
    projectId: 'comments-d4079',
    authDomain: 'comments-d4079.firebaseapp.com',
    storageBucket: 'comments-d4079.appspot.com',
    measurementId: 'G-7EDBPZ467J',
  );
}
